name: 'mediapulse'
version: '1.0.0'
config-version: 2

profile: 'mediapulse'

model-paths: ["models"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  mediapulse:
    staging:
      +materialized: view
      +schema: staging
    marts:
      +materialized: table
      +schema: marts
